#!/usr/bin/env python3
"""Generate or verify the exact V6S IMPL-02 external-review candidate."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


MANIFEST_RELATIVE = (
    "docs/09-审计与整改/UCN_V6S_IMPL_02_外审候选清单.sha256"
)
REQUIRED = (
    "CMakeLists.txt",
    "docs/00-项目管理/00-任务表.md",
    "docs/00-项目管理/01-项目操作记录.md",
    "docs/08-实现与验证/版本演进/UCN_V6S_IMPL_00_共同基础实施与自审报告.md",
    "docs/08-实现与验证/版本演进/UCN_V6S_IMPL_01_最小静态通信实施与自审报告.md",
    "docs/08-实现与验证/版本演进/UCN_V6S_IMPL_02_统一持久化基础实施与自审报告.md",
    "docs/源码阅读指南/06-公共函数签名索引.md",
    "include/ucn/ucn_persistence.h",
    "src/internal/ucn_persistence.h",
    "src/internal/ucn_persistence_coordinator.h",
    "src/persistence/ucn_persistence.c",
    "src/persistence/ucn_persistence_codec.c",
    "src/persistence/ucn_persistence_coordinator.c",
    "tests/simplified/test_persistence.c",
    "tests/simplified/test_persistence_codec.c",
    "tests/simplified/test_persistence_concurrency.c",
    "tests/simplified/test_persistence_coordinator.c",
    "tests/simplified/test_persistence_resources.c",
)


def add_glob(paths: set[Path], root: Path, pattern: str) -> None:
    paths.update(path.resolve() for path in root.glob(pattern) if path.is_file())


def candidate_paths(root: Path) -> list[Path]:
    paths: set[Path] = set()
    for relative in REQUIRED:
        path = (root / relative).resolve()
        if not path.is_file():
            raise FileNotFoundError(path)
        paths.add(path)

    for pattern in (
        ".gitignore",
        "cmake/*.in",
        "include/ucn/*.h",
        "src/core/*.c",
        "src/adapter/*.c",
        "src/runtime/*.c",
        "src/wire/*.c",
        "src/persistence/*.c",
        "src/internal/*.h",
        "tests/simplified/**/*",
        "rust/tests/conformance/*.h",
        "tools/v6/*.py",
        "tools/v6/*.cmake",
        "tools/v6/*.sh",
        "docs/10-理论与规划/建议方案/UCN_v6_V6S_00_简化版实施合同冻结/*.md",
        "docs/10-理论与规划/建议方案/UCN_v6_逻辑模型与伪代码/*.md",
    ):
        add_glob(paths, root, pattern)

    for relative in (
        "src/v6/security/ucn_v6_security.c",
        "tests/v6/install_consumer/main.c",
        "docs/09-审计与整改/UCN_V6_简化文档候选清单.sha256",
    ):
        path = (root / relative).resolve()
        if not path.is_file():
            raise FileNotFoundError(path)
        paths.add(path)

    manifest = (root / MANIFEST_RELATIVE).resolve()
    paths.discard(manifest)
    return sorted(paths, key=lambda path: path.relative_to(root).as_posix())


def render(root: Path) -> tuple[str, list[tuple[Path, bytes]]]:
    members: list[tuple[Path, bytes]] = []
    lines = [
        "# UCN V6S IMPL-02 exact external-review candidate manifest",
        "# Generated by tools/v6/generate_v6s_impl02_manifest.py",
        "# Format: SHA256  BYTES  UTF-8-RELATIVE-PATH",
    ]
    for path in candidate_paths(root):
        data = path.read_bytes()
        relative = path.relative_to(root).as_posix()
        members.append((path, data))
        lines.append(
            f"{hashlib.sha256(data).hexdigest().upper()}  {len(data)}  {relative}"
        )
    return "\n".join(lines) + "\n", members


def mutation_selftest(
    root: Path, rendered: str, members: list[tuple[Path, bytes]]
) -> bool:
    entries = {
        line.split("  ", 2)[2]: line.split("  ", 2)[0]
        for line in rendered.splitlines()
        if line and not line.startswith("#")
    }
    for path, data in members:
        if not data:
            return False
        relative = path.relative_to(root).as_posix()
        if relative not in entries:
            return False
        mutated = bytearray(data)
        mutated[len(mutated) // 2] ^= 1
        if hashlib.sha256(mutated).hexdigest().upper() == entries[relative]:
            return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True)
    parser.add_argument("--output", default=MANIFEST_RELATIVE)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    output = (root / args.output).resolve()
    try:
        rendered, members = render(root)
    except FileNotFoundError as error:
        print(f"V6S_IMPL02_MANIFEST_MISSING {error}")
        return 1
    if not mutation_selftest(root, rendered, members):
        print("V6S_IMPL02_MANIFEST_SELFTEST_FAILED")
        return 1
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
            print(f"V6S_IMPL02_MANIFEST_STALE {output}")
            return 1
        digest = hashlib.sha256(output.read_bytes()).hexdigest().upper()
        print(
            f"V6S_IMPL02_MANIFEST_OK entries={len(members)} sha256={digest} "
            f"mutations={len(members)}/{len(members)}"
        )
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8", newline="\n")
    digest = hashlib.sha256(output.read_bytes()).hexdigest().upper()
    print(
        f"V6S_IMPL02_MANIFEST_OK entries={len(members)} sha256={digest} "
        f"mutations={len(members)}/{len(members)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
