#!/usr/bin/env python3
"""Generate or verify the exact V6S-00 external-review candidate manifest."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


PROPOSAL_NAMES = (
    "README.md",
    "UCN_v6_最终协议架构与破坏性重构_RFC.md",
    "UCN_v6_低开销统一Wire重构多方案评估.md",
    "UCN_v6_低开销统一Wire各Contract字段与运行机制详细设计.md",
    "UCN_v6_可裁剪模块边界依赖资源与静态装配详细设计.md",
    "UCN_v6_面向用户意图的自动传输策略与配置接口详细设计.md",
)

BOUNDARY_AND_EVIDENCE = (
    "docs/10-理论与规划/建议方案/UCN_v6_Core_Wire_精确格式_RFC.md",
    "docs/09-审计与整改/UCN_V6_简化文档收口与全体自审报告_2026-09-08.md",
    "docs/00-项目管理/00-任务表.md",
    "docs/00-项目管理/01-项目操作记录.md",
    "docs/00-项目管理/04-UCN后续主要工作与分阶段实施路线图.md",
    "docs/00-项目管理/06-V6简化版分支基线与实施入口.md",
    "docs/calltree/README.md",
    "docs/源码阅读指南/06-公共函数签名索引.md",
    "tools/v6/check_v6_current_docs.py",
    "tools/v6/check_v6s_freeze_contracts.py",
    "tools/v6/check_v6s_wire_contract.py",
    "tools/v6/generate_v6_simplified_docs_manifest.py",
)

AUTHORIZED_REMEDIATIONS = (
    "src/v6/identity/ucn_v6_bootstrap.c",
    "src/v6/runtime/ucn_v6_runtime.c",
    "src/v6/security/ucn_v6_security.c",
    "tests/v6/test_v6_identity.c",
    "tests/v6/test_v6_security.c",
)


def candidate_paths(root: Path) -> list[Path]:
    proposal = root / "docs" / "10-理论与规划" / "建议方案"
    logic = proposal / "UCN_v6_逻辑模型与伪代码"
    paths = [proposal / name for name in PROPOSAL_NAMES]
    paths.extend(sorted(logic.glob("*.md")))
    paths.extend(sorted(
        (proposal / "UCN_v6_V6S_00_简化版实施合同冻结").glob("*.md")
    ))
    paths.extend(root / relative for relative in BOUNDARY_AND_EVIDENCE)
    paths.extend(root / relative for relative in AUTHORIZED_REMEDIATIONS)
    return sorted(set(path.resolve() for path in paths))


def render(root: Path) -> str:
    lines = [
        "# UCN V6S-00 exact external-review candidate manifest",
        "# Generated by tools/v6/generate_v6_simplified_docs_manifest.py",
        "# Format: SHA256  BYTES  UTF-8-RELATIVE-PATH",
    ]
    for path in candidate_paths(root):
        if not path.is_file():
            raise FileNotFoundError(path)
        data = path.read_bytes()
        relative = path.relative_to(root).as_posix()
        lines.append(f"{hashlib.sha256(data).hexdigest().upper()}  {len(data)}  {relative}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    output = (root / args.output).resolve()
    expected = render(root)
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            print(f"V6_SIMPLIFIED_MANIFEST_STALE {output}")
            return 1
        print(f"V6_SIMPLIFIED_MANIFEST_OK entries={len(expected.splitlines()) - 3}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8", newline="\n")
    print(f"V6_SIMPLIFIED_MANIFEST_OK entries={len(expected.splitlines()) - 3}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
