#ifndef UCN_TEST_SERVICE_QUEUE_DEPTH
#error "UCN_TEST_SERVICE_QUEUE_DEPTH must be provided by the configure gate"
#endif

#define UCN_SERVICE_REMOTE_TX_Q0_DEPTH UCN_TEST_SERVICE_QUEUE_DEPTH
#define UCN_SERVICE_REMOTE_TX_Q1_DEPTH UCN_TEST_SERVICE_QUEUE_DEPTH
#define UCN_SERVICE_REMOTE_TX_Q2_DEPTH UCN_TEST_SERVICE_QUEUE_DEPTH
#define UCN_SERVICE_REMOTE_TX_Q3_DEPTH UCN_TEST_SERVICE_QUEUE_DEPTH
#define UCN_SERVICE_Q0_INBOX_DEPTH UCN_TEST_SERVICE_QUEUE_DEPTH
#define UCN_SERVICE_Q2_INBOX_DEPTH UCN_TEST_SERVICE_QUEUE_DEPTH
#define UCN_SERVICE_Q3_INBOX_DEPTH UCN_TEST_SERVICE_QUEUE_DEPTH

#include "ucn/ucn_service.h"

int main(void)
{
    return UCN_TEST_SERVICE_QUEUE_DEPTH == UINT8_MAX ? 0 : 1;
}
