#ifndef UCN_CONFIG_H
#define UCN_CONFIG_H

#include <stddef.h>
#include <stdint.h>

/*
 * Global compile-time configuration entry.
 *
 * Precedence, from highest to lowest:
 *   1. compiler/CMake -D definitions;
 *   2. an optional product header named by UCN_USER_CONFIG_HEADER;
 *   3. the defaults listed in this file;
 *   4. the original per-header #ifndef defaults.
 *
 * Keep every translation unit that shares a public UCN object layout on the
 * same configuration.  UCN_CONFIG_NO_DEFAULTS is a test/integration escape
 * hatch: it skips this file's defaults and proves that the original headers
 * still provide their local fallbacks.
 */
#ifndef UCN_PROFILE_NANO
#define UCN_PROFILE_NANO 1
#endif
#ifndef UCN_PROFILE_LITE
#define UCN_PROFILE_LITE 2
#endif
#ifndef UCN_PROFILE_FULL
#define UCN_PROFILE_FULL 3
#endif

#ifdef UCN_USER_CONFIG_HEADER
#include UCN_USER_CONFIG_HEADER
#endif

#ifndef UCN_CONFIG_NO_DEFAULTS

/* Build and frame capacity. */
#ifndef UCN_PROTOCOL_VERSION
#define UCN_PROTOCOL_VERSION ((uint8_t)5U)
#endif
#ifndef UCN_PROFILE
#define UCN_PROFILE UCN_PROFILE_FULL
#endif
#ifndef UCN_FEATURE_SERVICE
#define UCN_FEATURE_SERVICE 1
#endif
#ifndef UCN_MAX_FRAME_BYTES
#define UCN_MAX_FRAME_BYTES ((size_t)256U)
#endif
#ifndef UCN_MAX_PAYLOAD_BYTES
#define UCN_MAX_PAYLOAD_BYTES \
    ((UCN_MAX_FRAME_BYTES > (size_t)32U) ? \
         (UCN_MAX_FRAME_BYTES - (size_t)32U) : (size_t)0U)
#endif
#ifndef UCN_MAX_HOPS
#define UCN_MAX_HOPS ((uint8_t)16U)
#endif

/* Optional UCN-Extended Transfer object.  These limits allocate storage only
 * in an application-owned ucn_transfer_t; ucn_node_t and the base Core do not
 * contain large-message buffers. */
#ifndef UCN_TRANSFER_MAX_MESSAGE_BYTES
#define UCN_TRANSFER_MAX_MESSAGE_BYTES ((size_t)8192U)
#endif
#ifndef UCN_TRANSFER_TX_SLOTS
#define UCN_TRANSFER_TX_SLOTS ((size_t)1U)
#endif
#ifndef UCN_TRANSFER_MAX_WINDOW
#define UCN_TRANSFER_MAX_WINDOW ((uint8_t)8U)
#endif
#ifndef UCN_TRANSFER_RX_SLOTS
#define UCN_TRANSFER_RX_SLOTS ((size_t)1U)
#endif
#ifndef UCN_TRANSFER_MAX_ENDPOINTS
#define UCN_TRANSFER_MAX_ENDPOINTS ((size_t)4U)
#endif
#ifndef UCN_TRANSFER_MAX_PEERS
#define UCN_TRANSFER_MAX_PEERS ((size_t)4U)
#endif
#ifndef UCN_TRANSFER_RECENT_COMPLETIONS
#define UCN_TRANSFER_RECENT_COMPLETIONS ((size_t)4U)
#endif
#ifndef UCN_TRANSFER_MAX_RETRIES
#define UCN_TRANSFER_MAX_RETRIES ((uint8_t)3U)
#endif
#ifndef UCN_TRANSFER_ACK_TIMEOUT_MS
#define UCN_TRANSFER_ACK_TIMEOUT_MS ((uint32_t)250U)
#endif
#ifndef UCN_TRANSFER_RX_TIMEOUT_MS
#define UCN_TRANSFER_RX_TIMEOUT_MS ((uint32_t)5000U)
#endif
#ifndef UCN_TRANSFER_COMPLETED_HOLD_MS
#define UCN_TRANSFER_COMPLETED_HOLD_MS ((uint32_t)30000U)
#endif
#ifndef UCN_TRANSFER_RECENT_COMPLETION_MS
#define UCN_TRANSFER_RECENT_COMPLETION_MS ((uint32_t)5000U)
#endif
#ifndef UCN_TRANSFER_MIN_FRAGMENT_DATA_BYTES
#define UCN_TRANSFER_MIN_FRAGMENT_DATA_BYTES ((uint16_t)16U)
#endif

/* Optional Extended Cluster control plane.  These values affect only products
 * that instantiate and link ucn_cluster_t; Core/Node storage is unchanged. */
#ifndef UCN_CLUSTER_MAX_PEERS
#define UCN_CLUSTER_MAX_PEERS ((size_t)8U)
#endif
#ifndef UCN_CLUSTER_MAX_CANDIDATES
#define UCN_CLUSTER_MAX_CANDIDATES ((size_t)8U)
#endif
#ifndef UCN_CLUSTER_MAX_MEMBERS
#define UCN_CLUSTER_MAX_MEMBERS ((size_t)16U)
#endif
/* Host/MCU compile-time guard for the fixed Cluster Owner object. Products
 * with a tighter verified budget may override this before including UCN.
 * The default intentionally leaves bounded headroom over the current Host
 * x64 ABI; it is not a claim about a particular MCU ABI. */
#ifndef UCN_CLUSTER_STORAGE_BUDGET_BYTES
#define UCN_CLUSTER_STORAGE_BUDGET_BYTES ((size_t)2048U)
#endif
#ifndef UCN_CLUSTER_OBSERVATION_MS
#define UCN_CLUSTER_OBSERVATION_MS UINT32_C(5000)
#endif
#ifndef UCN_CLUSTER_RECOVERY_OBSERVATION_MS
#define UCN_CLUSTER_RECOVERY_OBSERVATION_MS UINT32_C(5000)
#endif
#ifndef UCN_CLUSTER_ELECTION_WINDOW_MS
#define UCN_CLUSTER_ELECTION_WINDOW_MS UINT32_C(3000)
#endif
#ifndef UCN_CLUSTER_ADVERTISE_INTERVAL_MS
#define UCN_CLUSTER_ADVERTISE_INTERVAL_MS UINT32_C(1000)
#endif
#ifndef UCN_CLUSTER_JOIN_RETRY_MS
#define UCN_CLUSTER_JOIN_RETRY_MS UINT32_C(1000)
#endif
#ifndef UCN_CLUSTER_KEEPALIVE_INTERVAL_MS
#define UCN_CLUSTER_KEEPALIVE_INTERVAL_MS UINT32_C(2000)
#endif
#ifndef UCN_CLUSTER_LEASE_MS
#define UCN_CLUSTER_LEASE_MS UINT32_C(8000)
#endif
#ifndef UCN_CLUSTER_PROVISIONAL_TIMEOUT_MS
#define UCN_CLUSTER_PROVISIONAL_TIMEOUT_MS UINT32_C(10000)
#endif
#ifndef UCN_CLUSTER_HEAD_MIN_TENURE_MS
#define UCN_CLUSTER_HEAD_MIN_TENURE_MS UINT32_C(30000)
#endif
#ifndef UCN_CLUSTER_SWITCH_IMPROVEMENT_PERCENT
#define UCN_CLUSTER_SWITCH_IMPROVEMENT_PERCENT ((uint8_t)20U)
#endif
#ifndef UCN_CLUSTER_SWITCH_REQUIRED_SAMPLES
#define UCN_CLUSTER_SWITCH_REQUIRED_SAMPLES ((uint8_t)3U)
#endif

/* Explicit fast-recovery timing profile for low-loss, fixed wired products.
 * It is opt-in at runtime through ucn_cluster_config_apply_timing_profile();
 * the conservative defaults above remain the default for every product. */
#ifndef UCN_CLUSTER_FAST_OBSERVATION_MS
#define UCN_CLUSTER_FAST_OBSERVATION_MS UINT32_C(1000)
#endif
#ifndef UCN_CLUSTER_FAST_RECOVERY_OBSERVATION_MS
#define UCN_CLUSTER_FAST_RECOVERY_OBSERVATION_MS UINT32_C(500)
#endif
#ifndef UCN_CLUSTER_FAST_ELECTION_WINDOW_MS
#define UCN_CLUSTER_FAST_ELECTION_WINDOW_MS UINT32_C(1000)
#endif
#ifndef UCN_CLUSTER_FAST_ADVERTISE_INTERVAL_MS
#define UCN_CLUSTER_FAST_ADVERTISE_INTERVAL_MS UINT32_C(250)
#endif
#ifndef UCN_CLUSTER_FAST_JOIN_RETRY_MS
#define UCN_CLUSTER_FAST_JOIN_RETRY_MS UINT32_C(250)
#endif
#ifndef UCN_CLUSTER_FAST_KEEPALIVE_INTERVAL_MS
#define UCN_CLUSTER_FAST_KEEPALIVE_INTERVAL_MS UINT32_C(500)
#endif
#ifndef UCN_CLUSTER_FAST_LEASE_MS
#define UCN_CLUSTER_FAST_LEASE_MS UINT32_C(2000)
#endif
#ifndef UCN_CLUSTER_FAST_PROVISIONAL_TIMEOUT_MS
#define UCN_CLUSTER_FAST_PROVISIONAL_TIMEOUT_MS UINT32_C(3000)
#endif
#ifndef UCN_CLUSTER_FAST_HEAD_MIN_TENURE_MS
#define UCN_CLUSTER_FAST_HEAD_MIN_TENURE_MS UINT32_C(10000)
#endif

/* Optional C06 Cluster Federation.  These tables will live only in a
 * product-owned ucn_cluster_federation_t; neither ucn_node_t nor the Core
 * archive allocates Directory or Tunnel state. */
#ifndef UCN_CLUSTER_FED_MAX_DIRECTORY_AUTHORITIES
#define UCN_CLUSTER_FED_MAX_DIRECTORY_AUTHORITIES ((size_t)2U)
#endif
#ifndef UCN_CLUSTER_FED_MAX_LOCAL_LOCATORS
#define UCN_CLUSTER_FED_MAX_LOCAL_LOCATORS ((size_t)17U)
#endif
#ifndef UCN_CLUSTER_FED_MAX_DIRECTORY_RECORDS
#define UCN_CLUSTER_FED_MAX_DIRECTORY_RECORDS ((size_t)32U)
#endif
#ifndef UCN_CLUSTER_FED_MAX_LOCATOR_CACHE
#define UCN_CLUSTER_FED_MAX_LOCATOR_CACHE ((size_t)16U)
#endif
#ifndef UCN_CLUSTER_FED_MAX_NEXT_CLUSTERS
#define UCN_CLUSTER_FED_MAX_NEXT_CLUSTERS ((size_t)8U)
#endif
#ifndef UCN_CLUSTER_FED_MAX_PENDING
#define UCN_CLUSTER_FED_MAX_PENDING ((size_t)2U)
#endif
#ifndef UCN_CLUSTER_FED_MAX_SEEN_TRANSACTIONS
#define UCN_CLUSTER_FED_MAX_SEEN_TRANSACTIONS ((size_t)8U)
#endif
#ifndef UCN_CLUSTER_FED_DIRECTORY_LEASE_MS
#define UCN_CLUSTER_FED_DIRECTORY_LEASE_MS UINT32_C(8000)
#endif
#ifndef UCN_CLUSTER_FED_LOCATOR_REFRESH_MS
#define UCN_CLUSTER_FED_LOCATOR_REFRESH_MS UINT32_C(2000)
#endif
#ifndef UCN_CLUSTER_FED_QUERY_TIMEOUT_MS
#define UCN_CLUSTER_FED_QUERY_TIMEOUT_MS UINT32_C(1000)
#endif
#ifndef UCN_CLUSTER_FED_TRANSACTION_LEASE_MS
#define UCN_CLUSTER_FED_TRANSACTION_LEASE_MS UINT32_C(3000)
#endif

/* Adapter and physical identity buffers. */
#ifndef UCN_ADAPTER_RX_QUEUE_DEPTH
#define UCN_ADAPTER_RX_QUEUE_DEPTH 2U
#endif
#ifndef UCN_ADAPTER_PHYSICAL_ADDRESS_MAX
#define UCN_ADAPTER_PHYSICAL_ADDRESS_MAX 8U
#endif

/* Optional standard event Runtime.  Storage is allocated only when a product
 * instantiates ucn_event_runtime_t; it is not embedded in ucn_node_t. */
#ifndef UCN_EVENT_RUNTIME_MAX_SOURCES
#define UCN_EVENT_RUNTIME_MAX_SOURCES 8U
#endif
#ifndef UCN_EVENT_RUNTIME_DEFAULT_DRAIN_ROUNDS
#define UCN_EVENT_RUNTIME_DEFAULT_DRAIN_ROUNDS 8U
#endif
#ifndef UCN_EVENT_RUNTIME_DEFAULT_SOURCE_BUDGET
#define UCN_EVENT_RUNTIME_DEFAULT_SOURCE_BUDGET 4U
#endif

/* Optional caller-storage Stream Carrier Source for UART/RS-485/USB CDC. */
#ifndef UCN_STREAM_SOURCE_DEFAULT_RING_BYTES
#define UCN_STREAM_SOURCE_DEFAULT_RING_BYTES 512U
#endif
#ifndef UCN_STREAM_SOURCE_DEFAULT_BYTE_BUDGET
#define UCN_STREAM_SOURCE_DEFAULT_BYTE_BUDGET 512U
#endif
#ifndef UCN_STREAM_SOURCE_DEFAULT_ERROR_BUDGET
#define UCN_STREAM_SOURCE_DEFAULT_ERROR_BUDGET 4U
#endif
#ifndef UCN_STREAM_SOURCE_READ_CHUNK_BYTES
#define UCN_STREAM_SOURCE_READ_CHUNK_BYTES 32U
#endif

/* Optional caller-storage CAN/CAN-FD Frame Source. */
#ifndef UCN_CAN_SOURCE_DEFAULT_RING_FRAMES
#define UCN_CAN_SOURCE_DEFAULT_RING_FRAMES 8U
#endif
#ifndef UCN_CAN_SOURCE_DEFAULT_REASSEMBLY_SLOTS
#define UCN_CAN_SOURCE_DEFAULT_REASSEMBLY_SLOTS 2U
#endif
#ifndef UCN_CAN_SOURCE_DEFAULT_REASSEMBLY_TIMEOUT_MS
#define UCN_CAN_SOURCE_DEFAULT_REASSEMBLY_TIMEOUT_MS 250U
#endif

/* Core queues, scheduling and static tables. */
#ifndef UCN_SECURITY_REQUIRED_BY_DEFAULT
#define UCN_SECURITY_REQUIRED_BY_DEFAULT 0
#endif
#ifndef UCN_MAX_LINKS
#define UCN_MAX_LINKS ((size_t)4U)
#endif
#ifndef UCN_TX_Q0_DEPTH
#define UCN_TX_Q0_DEPTH ((size_t)4U)
#endif
#ifndef UCN_TX_Q1_DEPTH
#define UCN_TX_Q1_DEPTH ((size_t)4U)
#endif
#ifndef UCN_TX_Q2_DEPTH
#define UCN_TX_Q2_DEPTH ((size_t)2U)
#endif
#ifndef UCN_TX_Q3_DEPTH
#define UCN_TX_Q3_DEPTH ((size_t)1U)
#endif
#ifndef UCN_BUSINESS_TX_BURST_BEFORE_MAINTENANCE
#define UCN_BUSINESS_TX_BURST_BEFORE_MAINTENANCE ((uint8_t)4U)
#endif
#ifndef UCN_MAX_STEP_INTERVAL_MS
#define UCN_MAX_STEP_INTERVAL_MS UINT32_C(10)
#endif
#ifndef UCN_Q0_BACKPRESSURE_MAX_RETRIES
#define UCN_Q0_BACKPRESSURE_MAX_RETRIES ((uint8_t)3U)
#endif
#ifndef UCN_Q0_BACKPRESSURE_RETRY_INTERVAL_MS
#define UCN_Q0_BACKPRESSURE_RETRY_INTERVAL_MS UINT32_C(5)
#endif
#ifndef UCN_Q0_ROUTE_WAIT_RETRY_INTERVAL_MS
#define UCN_Q0_ROUTE_WAIT_RETRY_INTERVAL_MS UINT32_C(50)
#endif
#ifndef UCN_MAX_ROUTES
#define UCN_MAX_ROUTES ((size_t)8U)
#endif

/* Duplicate and route-request state. */
#ifndef UCN_DUPLICATE_SOURCE_WINDOWS
#ifdef UCN_SEEN_CACHE_SIZE
#define UCN_DUPLICATE_SOURCE_WINDOWS UCN_SEEN_CACHE_SIZE
#elif UCN_PROFILE == UCN_PROFILE_NANO
#define UCN_DUPLICATE_SOURCE_WINDOWS ((size_t)4U)
#elif UCN_PROFILE == UCN_PROFILE_LITE
#define UCN_DUPLICATE_SOURCE_WINDOWS ((size_t)16U)
#else
#define UCN_DUPLICATE_SOURCE_WINDOWS ((size_t)32U)
#endif
#endif
#ifndef UCN_DUPLICATE_WINDOW_BITS
#if UCN_PROFILE == UCN_PROFILE_FULL
#define UCN_DUPLICATE_WINDOW_BITS 64U
#else
#define UCN_DUPLICATE_WINDOW_BITS 32U
#endif
#endif
#ifndef UCN_DUPLICATE_SOURCE_TIMEOUT_MS
#define UCN_DUPLICATE_SOURCE_TIMEOUT_MS UINT32_C(60000)
#endif
#ifndef UCN_SEEN_CACHE_SIZE
#define UCN_SEEN_CACHE_SIZE UCN_DUPLICATE_SOURCE_WINDOWS
#endif
#ifndef UCN_RREQ_CACHE_SIZE
#if UCN_PROFILE == UCN_PROFILE_FULL
#define UCN_RREQ_CACHE_SIZE ((size_t)16U)
#else
#define UCN_RREQ_CACHE_SIZE ((size_t)8U)
#endif
#endif
#ifndef UCN_RREQ_CACHE_TIMEOUT_MS
#define UCN_RREQ_CACHE_TIMEOUT_MS UINT32_C(5000)
#endif

/* Routing, candidate probing and pending first-packet state. */
#ifndef UCN_MAX_ROUTE_DISCOVERIES
#define UCN_MAX_ROUTE_DISCOVERIES ((size_t)4U)
#endif
#ifndef UCN_MAX_CANDIDATE_ROUTES
#define UCN_MAX_CANDIDATE_ROUTES ((size_t)8U)
#endif
#ifndef UCN_ROUTE_ENTRY_LIFETIME_MS
#define UCN_ROUTE_ENTRY_LIFETIME_MS UINT32_C(30000)
#endif
#ifndef UCN_ROUTE_REQUEST_TIMEOUT_MS
#define UCN_ROUTE_REQUEST_TIMEOUT_MS UINT32_C(1000)
#endif
#ifndef UCN_ROUTE_REQUEST_MIN_INTERVAL_MS
#define UCN_ROUTE_REQUEST_MIN_INTERVAL_MS UINT32_C(100)
#endif
#ifndef UCN_ROUTE_REFRESH_ADVANCE_MS
#define UCN_ROUTE_REFRESH_ADVANCE_MS UINT32_C(6000)
#endif
#ifndef UCN_ROUTE_REFRESH_MIN_INTERVAL_MS
#define UCN_ROUTE_REFRESH_MIN_INTERVAL_MS UINT32_C(5000)
#endif
#ifndef UCN_ROUTE_CANDIDATE_TIMEOUT_MS
#define UCN_ROUTE_CANDIDATE_TIMEOUT_MS UINT32_C(3000)
#endif
#ifndef UCN_PATH_PROBE_REQUIRED_ACKS
#define UCN_PATH_PROBE_REQUIRED_ACKS ((uint8_t)3U)
#endif
#ifndef UCN_PATH_PROBE_INTERVAL_MS
#define UCN_PATH_PROBE_INTERVAL_MS UINT32_C(100)
#endif
#ifndef UCN_ROUTE_SWITCH_IMPROVEMENT_PERCENT
#define UCN_ROUTE_SWITCH_IMPROVEMENT_PERCENT ((uint8_t)20U)
#endif
#ifndef UCN_ROUTE_EPOCH_GRACE_MS
#define UCN_ROUTE_EPOCH_GRACE_MS UINT32_C(1000)
#endif
#ifndef UCN_UNKNOWN_LINK_ROUTE_COST
#define UCN_UNKNOWN_LINK_ROUTE_COST UCN_LINK_ROUTE_COST_UNKNOWN
#endif
#ifndef UCN_PENDING_Q1_DEPTH
#define UCN_PENDING_Q1_DEPTH ((size_t)4U)
#endif
#ifndef UCN_PENDING_Q1_TIMEOUT_MS
#define UCN_PENDING_Q1_TIMEOUT_MS UINT32_C(1000)
#endif
#ifndef UCN_SEQUENCE_ROTATION_THRESHOLD
#define UCN_SEQUENCE_ROTATION_THRESHOLD (UINT32_MAX - UINT32_C(1024))
#endif

/* Local-origin and inbound control-plane budgets. */
#ifndef UCN_CONTROL_TOKEN_BURST
#define UCN_CONTROL_TOKEN_BURST ((uint8_t)4U)
#endif
#ifndef UCN_CONTROL_TOKEN_REFILL_MS
#define UCN_CONTROL_TOKEN_REFILL_MS UINT32_C(100)
#endif
#ifndef UCN_ROUTE_REQUEST_RX_TOKEN_BURST
#define UCN_ROUTE_REQUEST_RX_TOKEN_BURST ((uint8_t)5U)
#endif
#ifndef UCN_ROUTE_REQUEST_RX_TOKEN_REFILL_MS
#define UCN_ROUTE_REQUEST_RX_TOKEN_REFILL_MS UINT32_C(200)
#endif
#ifndef UCN_HEARTBEAT_RX_TOKEN_BURST
#define UCN_HEARTBEAT_RX_TOKEN_BURST ((uint8_t)4U)
#endif
#ifndef UCN_HEARTBEAT_RX_TOKEN_REFILL_MS
#define UCN_HEARTBEAT_RX_TOKEN_REFILL_MS UINT32_C(100)
#endif
#ifndef UCN_PATH_TRACE_RX_TOKEN_BURST
#define UCN_PATH_TRACE_RX_TOKEN_BURST ((uint8_t)1U)
#endif
#ifndef UCN_PATH_TRACE_RX_TOKEN_REFILL_MS
#define UCN_PATH_TRACE_RX_TOKEN_REFILL_MS UINT32_C(1000)
#endif
#ifndef UCN_PATH_CONTROL_RX_SOURCE_DEPTH
#define UCN_PATH_CONTROL_RX_SOURCE_DEPTH ((size_t)4U)
#endif
#ifndef UCN_PATH_CONTROL_RX_TOKEN_BURST
#define UCN_PATH_CONTROL_RX_TOKEN_BURST ((uint8_t)4U)
#endif
#ifndef UCN_PATH_CONTROL_RX_TOKEN_REFILL_MS
#define UCN_PATH_CONTROL_RX_TOKEN_REFILL_MS UINT32_C(1000)
#endif
#ifndef UCN_PATH_CONTROL_RX_SOURCE_IDLE_MS
#define UCN_PATH_CONTROL_RX_SOURCE_IDLE_MS UINT32_C(60000)
#endif

/* On-demand path, snapshot and policy diagnostics. */
#ifndef UCN_PATH_TRACE_PENDING_DEPTH
#define UCN_PATH_TRACE_PENDING_DEPTH ((size_t)2U)
#endif
#ifndef UCN_PATH_TRACE_REVERSE_DEPTH
#define UCN_PATH_TRACE_REVERSE_DEPTH ((size_t)4U)
#endif
#ifndef UCN_PATH_TRACE_TIMEOUT_MS
#define UCN_PATH_TRACE_TIMEOUT_MS UINT32_C(1000)
#endif
#ifndef UCN_PATH_TRACE_TOKEN_BURST
#define UCN_PATH_TRACE_TOKEN_BURST ((uint8_t)1U)
#endif
#ifndef UCN_PATH_TRACE_TOKEN_REFILL_MS
#define UCN_PATH_TRACE_TOKEN_REFILL_MS UINT32_C(1000)
#endif
#ifndef UCN_NODE_SNAPSHOT_MAX_RESULTS
#define UCN_NODE_SNAPSHOT_MAX_RESULTS ((size_t)8U)
#endif
#ifndef UCN_NODE_SNAPSHOT_PENDING_DEPTH
#define UCN_NODE_SNAPSHOT_PENDING_DEPTH ((size_t)1U)
#endif
#ifndef UCN_NODE_SNAPSHOT_REVERSE_DEPTH
#define UCN_NODE_SNAPSHOT_REVERSE_DEPTH ((size_t)2U)
#endif
#ifndef UCN_NODE_SNAPSHOT_REPLY_QUEUE_DEPTH
#define UCN_NODE_SNAPSHOT_REPLY_QUEUE_DEPTH ((size_t)2U)
#endif
#ifndef UCN_NODE_SNAPSHOT_TIMEOUT_MS
#define UCN_NODE_SNAPSHOT_TIMEOUT_MS UINT32_C(2000)
#endif
#ifndef UCN_NODE_SNAPSHOT_TOKEN_BURST
#define UCN_NODE_SNAPSHOT_TOKEN_BURST ((uint8_t)1U)
#endif
#ifndef UCN_NODE_SNAPSHOT_TOKEN_REFILL_MS
#define UCN_NODE_SNAPSHOT_TOKEN_REFILL_MS UINT32_C(10000)
#endif
#ifndef UCN_NODE_SNAPSHOT_REPLY_JITTER_MS
#define UCN_NODE_SNAPSHOT_REPLY_JITTER_MS UINT32_C(200)
#endif
#ifndef UCN_POLICY_DIAGNOSTIC_PENDING_DEPTH
#define UCN_POLICY_DIAGNOSTIC_PENDING_DEPTH ((size_t)2U)
#endif
#ifndef UCN_POLICY_DIAGNOSTIC_REPLY_QUEUE_DEPTH
#define UCN_POLICY_DIAGNOSTIC_REPLY_QUEUE_DEPTH ((size_t)2U)
#endif
#ifndef UCN_POLICY_DIAGNOSTIC_TIMEOUT_MS
#define UCN_POLICY_DIAGNOSTIC_TIMEOUT_MS UINT32_C(1000)
#endif
#ifndef UCN_POLICY_DIAGNOSTIC_TOKEN_BURST
#define UCN_POLICY_DIAGNOSTIC_TOKEN_BURST ((uint8_t)1U)
#endif
#ifndef UCN_POLICY_DIAGNOSTIC_TOKEN_REFILL_MS
#define UCN_POLICY_DIAGNOSTIC_TOKEN_REFILL_MS UINT32_C(1000)
#endif

/* Neighbor, heartbeat and multi-bearer quality. */
#ifndef UCN_MAX_NEIGHBORS
#define UCN_MAX_NEIGHBORS ((size_t)8U)
#endif
#ifndef UCN_MAX_BEARERS_PER_NEIGHBOR
#define UCN_MAX_BEARERS_PER_NEIGHBOR ((size_t)2U)
#endif
#ifndef UCN_NEIGHBOR_CANDIDATE_TIMEOUT_MS
#define UCN_NEIGHBOR_CANDIDATE_TIMEOUT_MS UINT32_C(5000)
#endif
#ifndef UCN_HEARTBEAT_INTERVAL_MS
#define UCN_HEARTBEAT_INTERVAL_MS UINT32_C(1000)
#endif
#ifndef UCN_NEIGHBOR_SUSPECT_TIMEOUT_MS
#define UCN_NEIGHBOR_SUSPECT_TIMEOUT_MS UINT32_C(3000)
#endif
#ifndef UCN_NEIGHBOR_REMOVE_TIMEOUT_MS
#define UCN_NEIGHBOR_REMOVE_TIMEOUT_MS UINT32_C(4000)
#endif
/* Optional per-Link fast liveness class.  DEFAULT continues to use the three
 * values above, so zero-initialized and existing product Links are unchanged.
 * FAST is intended for low-latency wired Bearers such as board-to-board UART
 * or RS-485. */
#ifndef UCN_LINK_LIVENESS_FAST_HEARTBEAT_INTERVAL_MS
#define UCN_LINK_LIVENESS_FAST_HEARTBEAT_INTERVAL_MS UINT32_C(250)
#endif
#ifndef UCN_LINK_LIVENESS_FAST_SUSPECT_TIMEOUT_MS
#define UCN_LINK_LIVENESS_FAST_SUSPECT_TIMEOUT_MS UINT32_C(1250)
#endif
#ifndef UCN_LINK_LIVENESS_FAST_REMOVE_TIMEOUT_MS
#define UCN_LINK_LIVENESS_FAST_REMOVE_TIMEOUT_MS UINT32_C(2000)
#endif
#ifndef UCN_BEARER_SWITCH_IMPROVEMENT_PERCENT
#define UCN_BEARER_SWITCH_IMPROVEMENT_PERCENT \
    UCN_ROUTE_SWITCH_IMPROVEMENT_PERCENT
#endif
#ifndef UCN_BEARER_QUALITY_SAMPLE_INTERVAL_MS
#define UCN_BEARER_QUALITY_SAMPLE_INTERVAL_MS UINT32_C(500)
#endif
#ifndef UCN_BEARER_QUALITY_STABLE_SAMPLES
#define UCN_BEARER_QUALITY_STABLE_SAMPLES ((uint8_t)3U)
#endif
#ifndef UCN_BEARER_QUALITY_PROBE_REQUIRED_ACKS
#define UCN_BEARER_QUALITY_PROBE_REQUIRED_ACKS ((uint8_t)2U)
#endif
#ifndef UCN_BEARER_QUALITY_PROBE_MAX_ATTEMPTS
#define UCN_BEARER_QUALITY_PROBE_MAX_ATTEMPTS ((uint8_t)3U)
#endif
#ifndef UCN_BEARER_QUALITY_PROBE_INTERVAL_MS
#define UCN_BEARER_QUALITY_PROBE_INTERVAL_MS UINT32_C(100)
#endif
#ifndef UCN_BEARER_QUALITY_SWITCH_HOLD_MS
#define UCN_BEARER_QUALITY_SWITCH_HOLD_MS UINT32_C(3000)
#endif

/* Endpoint, explicit Path and policy tables. */
#ifndef UCN_MAX_ENDPOINT_HANDLERS
#define UCN_MAX_ENDPOINT_HANDLERS ((size_t)8U)
#endif
#ifndef UCN_MAX_ENDPOINT_SECURITY_POLICIES
#define UCN_MAX_ENDPOINT_SECURITY_POLICIES ((size_t)8U)
#endif
#ifndef UCN_MAX_PATH_FORWARD_ENTRIES
#define UCN_MAX_PATH_FORWARD_ENTRIES ((size_t)8U)
#endif
#ifndef UCN_MAX_ROUTE_POLICIES
#define UCN_MAX_ROUTE_POLICIES ((size_t)8U)
#endif
#ifndef UCN_MAX_POLICY_PATHS
#define UCN_MAX_POLICY_PATHS ((size_t)8U)
#endif
#ifndef UCN_MAX_POLICY_FLOWS
#define UCN_MAX_POLICY_FLOWS ((size_t)8U)
#endif
#ifndef UCN_POLICY_QUALITY_SAMPLE_INTERVAL_MS
#define UCN_POLICY_QUALITY_SAMPLE_INTERVAL_MS UINT32_C(500)
#endif
#ifndef UCN_POLICY_QUALITY_EWMA_ALPHA_PERCENT
#define UCN_POLICY_QUALITY_EWMA_ALPHA_PERCENT ((uint8_t)25U)
#endif
#ifndef UCN_POLICY_BALANCE_FLOW_LEASE_MS
#define UCN_POLICY_BALANCE_FLOW_LEASE_MS UINT32_C(2000)
#endif
#ifndef UCN_POLICY_BALANCE_QUEUE_PRESSURE_THRESHOLD_PER_MILLE
#define UCN_POLICY_BALANCE_QUEUE_PRESSURE_THRESHOLD_PER_MILLE ((uint16_t)800U)
#endif
#ifndef UCN_POLICY_BALANCE_CONGESTED_SAMPLE_LIMIT
#define UCN_POLICY_BALANCE_CONGESTED_SAMPLE_LIMIT ((uint8_t)3U)
#endif

/* Intra-node Service Router and Protocol Bridge. */
#ifndef UCN_SERVICE_MAX_BINDINGS
#define UCN_SERVICE_MAX_BINDINGS ((uint8_t)6U)
#endif
#ifndef UCN_SERVICE_MAX_PAYLOAD_BYTES
#define UCN_SERVICE_MAX_PAYLOAD_BYTES ((uint16_t)32U)
#endif
#ifndef UCN_SERVICE_REMOTE_TX_Q0_DEPTH
#define UCN_SERVICE_REMOTE_TX_Q0_DEPTH ((uint8_t)4U)
#endif
#ifndef UCN_SERVICE_REMOTE_TX_Q1_DEPTH
#define UCN_SERVICE_REMOTE_TX_Q1_DEPTH ((uint8_t)4U)
#endif
#ifndef UCN_SERVICE_REMOTE_TX_Q2_DEPTH
#define UCN_SERVICE_REMOTE_TX_Q2_DEPTH ((uint8_t)2U)
#endif
#ifndef UCN_SERVICE_REMOTE_TX_Q3_DEPTH
#define UCN_SERVICE_REMOTE_TX_Q3_DEPTH ((uint8_t)1U)
#endif
#ifndef UCN_SERVICE_MAX_Q0_BINDINGS
#define UCN_SERVICE_MAX_Q0_BINDINGS ((uint8_t)2U)
#endif
#ifndef UCN_SERVICE_MAX_Q1_BINDINGS
#define UCN_SERVICE_MAX_Q1_BINDINGS ((uint8_t)4U)
#endif
#ifndef UCN_SERVICE_MAX_Q2_BINDINGS
#define UCN_SERVICE_MAX_Q2_BINDINGS ((uint8_t)1U)
#endif
#ifndef UCN_SERVICE_MAX_Q3_BINDINGS
#define UCN_SERVICE_MAX_Q3_BINDINGS ((uint8_t)1U)
#endif
#ifndef UCN_SERVICE_Q0_INBOX_DEPTH
#define UCN_SERVICE_Q0_INBOX_DEPTH ((uint8_t)4U)
#endif
#ifndef UCN_SERVICE_Q2_INBOX_DEPTH
#define UCN_SERVICE_Q2_INBOX_DEPTH ((uint8_t)2U)
#endif
#ifndef UCN_SERVICE_Q3_INBOX_DEPTH
#define UCN_SERVICE_Q3_INBOX_DEPTH ((uint8_t)1U)
#endif
#ifndef UCN_SERVICE_BRIDGE_MAX_VALIDATORS
#define UCN_SERVICE_BRIDGE_MAX_VALIDATORS UCN_SERVICE_MAX_Q0_BINDINGS
#endif
#ifndef UCN_SERVICE_BRIDGE_REPLAY_DEPTH
#define UCN_SERVICE_BRIDGE_REPLAY_DEPTH ((uint8_t)4U)
#endif

#endif /* UCN_CONFIG_NO_DEFAULTS */

#endif /* UCN_CONFIG_H */
