#ifndef UCN_CONFIG_H
#define UCN_CONFIG_H

#include <stddef.h>
#include <stdint.h>

/*
 * Global compile-time configuration entry.
 *
 * Precedence, from highest to lowest:
 *   1. compiler/CMake -D definitions;
 *   2. an optional product header named by UCN_USER_CONFIG_HEADER;
 *   3. the defaults listed in this file;
 *   4. the original per-header #ifndef defaults.
 *
 * Keep every translation unit that shares a public UCN object layout on the
 * same configuration.  UCN_CONFIG_NO_DEFAULTS is a test/integration escape
 * hatch: it skips this file's defaults and proves that the original headers
 * still provide their local fallbacks.
 */
#ifndef UCN_PROFILE_NANO
#define UCN_PROFILE_NANO 1
#endif
#ifndef UCN_PROFILE_LITE
#define UCN_PROFILE_LITE 2
#endif
#ifndef UCN_PROFILE_FULL
#define UCN_PROFILE_FULL 3
#endif

#ifdef UCN_USER_CONFIG_HEADER
#include UCN_USER_CONFIG_HEADER
#endif

#ifndef UCN_CONFIG_NO_DEFAULTS

/* Build and frame capacity. */
#ifndef UCN_PROFILE
#define UCN_PROFILE UCN_PROFILE_FULL
#endif
#ifndef UCN_FEATURE_SERVICE
#define UCN_FEATURE_SERVICE 1
#endif
#ifndef UCN_MAX_FRAME_BYTES
#define UCN_MAX_FRAME_BYTES ((size_t)256U)
#endif
#ifndef UCN_MAX_PAYLOAD_BYTES
#define UCN_MAX_PAYLOAD_BYTES \
    ((UCN_MAX_FRAME_BYTES > (size_t)32U) ? \
         (UCN_MAX_FRAME_BYTES - (size_t)32U) : (size_t)0U)
#endif
#ifndef UCN_MAX_HOPS
#define UCN_MAX_HOPS ((uint8_t)16U)
#endif

/* Adapter and physical identity buffers. */
#ifndef UCN_ADAPTER_RX_QUEUE_DEPTH
#define UCN_ADAPTER_RX_QUEUE_DEPTH 2U
#endif
#ifndef UCN_ADAPTER_PHYSICAL_ADDRESS_MAX
#define UCN_ADAPTER_PHYSICAL_ADDRESS_MAX 8U
#endif

/* Core queues, scheduling and static tables. */
#ifndef UCN_SECURITY_REQUIRED_BY_DEFAULT
#define UCN_SECURITY_REQUIRED_BY_DEFAULT 0
#endif
#ifndef UCN_MAX_LINKS
#define UCN_MAX_LINKS ((size_t)4U)
#endif
#ifndef UCN_TX_Q0_DEPTH
#define UCN_TX_Q0_DEPTH ((size_t)4U)
#endif
#ifndef UCN_TX_Q1_DEPTH
#define UCN_TX_Q1_DEPTH ((size_t)4U)
#endif
#ifndef UCN_BUSINESS_TX_BURST_BEFORE_MAINTENANCE
#define UCN_BUSINESS_TX_BURST_BEFORE_MAINTENANCE ((uint8_t)4U)
#endif
#ifndef UCN_MAX_STEP_INTERVAL_MS
#define UCN_MAX_STEP_INTERVAL_MS UINT32_C(10)
#endif
#ifndef UCN_Q0_BACKPRESSURE_MAX_RETRIES
#define UCN_Q0_BACKPRESSURE_MAX_RETRIES ((uint8_t)3U)
#endif
#ifndef UCN_Q0_BACKPRESSURE_RETRY_INTERVAL_MS
#define UCN_Q0_BACKPRESSURE_RETRY_INTERVAL_MS UINT32_C(5)
#endif
#ifndef UCN_MAX_ROUTES
#define UCN_MAX_ROUTES ((size_t)8U)
#endif

/* Duplicate and route-request state. */
#ifndef UCN_DUPLICATE_SOURCE_WINDOWS
#ifdef UCN_SEEN_CACHE_SIZE
#define UCN_DUPLICATE_SOURCE_WINDOWS UCN_SEEN_CACHE_SIZE
#elif UCN_PROFILE == UCN_PROFILE_NANO
#define UCN_DUPLICATE_SOURCE_WINDOWS ((size_t)4U)
#elif UCN_PROFILE == UCN_PROFILE_LITE
#define UCN_DUPLICATE_SOURCE_WINDOWS ((size_t)16U)
#else
#define UCN_DUPLICATE_SOURCE_WINDOWS ((size_t)32U)
#endif
#endif
#ifndef UCN_DUPLICATE_WINDOW_BITS
#if UCN_PROFILE == UCN_PROFILE_FULL
#define UCN_DUPLICATE_WINDOW_BITS 64U
#else
#define UCN_DUPLICATE_WINDOW_BITS 32U
#endif
#endif
#ifndef UCN_DUPLICATE_SOURCE_TIMEOUT_MS
#define UCN_DUPLICATE_SOURCE_TIMEOUT_MS UINT32_C(60000)
#endif
#ifndef UCN_SEEN_CACHE_SIZE
#define UCN_SEEN_CACHE_SIZE UCN_DUPLICATE_SOURCE_WINDOWS
#endif
#ifndef UCN_RREQ_CACHE_SIZE
#if UCN_PROFILE == UCN_PROFILE_FULL
#define UCN_RREQ_CACHE_SIZE ((size_t)16U)
#else
#define UCN_RREQ_CACHE_SIZE ((size_t)8U)
#endif
#endif
#ifndef UCN_RREQ_CACHE_TIMEOUT_MS
#define UCN_RREQ_CACHE_TIMEOUT_MS UINT32_C(5000)
#endif

/* Routing, candidate probing and pending first-packet state. */
#ifndef UCN_MAX_ROUTE_DISCOVERIES
#define UCN_MAX_ROUTE_DISCOVERIES ((size_t)4U)
#endif
#ifndef UCN_MAX_CANDIDATE_ROUTES
#define UCN_MAX_CANDIDATE_ROUTES ((size_t)8U)
#endif
#ifndef UCN_ROUTE_ENTRY_LIFETIME_MS
#define UCN_ROUTE_ENTRY_LIFETIME_MS UINT32_C(30000)
#endif
#ifndef UCN_ROUTE_REQUEST_TIMEOUT_MS
#define UCN_ROUTE_REQUEST_TIMEOUT_MS UINT32_C(1000)
#endif
#ifndef UCN_ROUTE_REQUEST_MIN_INTERVAL_MS
#define UCN_ROUTE_REQUEST_MIN_INTERVAL_MS UINT32_C(100)
#endif
#ifndef UCN_ROUTE_REFRESH_ADVANCE_MS
#define UCN_ROUTE_REFRESH_ADVANCE_MS UINT32_C(6000)
#endif
#ifndef UCN_ROUTE_REFRESH_MIN_INTERVAL_MS
#define UCN_ROUTE_REFRESH_MIN_INTERVAL_MS UINT32_C(5000)
#endif
#ifndef UCN_ROUTE_CANDIDATE_TIMEOUT_MS
#define UCN_ROUTE_CANDIDATE_TIMEOUT_MS UINT32_C(3000)
#endif
#ifndef UCN_PATH_PROBE_REQUIRED_ACKS
#define UCN_PATH_PROBE_REQUIRED_ACKS ((uint8_t)3U)
#endif
#ifndef UCN_PATH_PROBE_INTERVAL_MS
#define UCN_PATH_PROBE_INTERVAL_MS UINT32_C(100)
#endif
#ifndef UCN_ROUTE_SWITCH_IMPROVEMENT_PERCENT
#define UCN_ROUTE_SWITCH_IMPROVEMENT_PERCENT ((uint8_t)20U)
#endif
#ifndef UCN_ROUTE_EPOCH_GRACE_MS
#define UCN_ROUTE_EPOCH_GRACE_MS UINT32_C(1000)
#endif
#ifndef UCN_UNKNOWN_LINK_ROUTE_COST
#define UCN_UNKNOWN_LINK_ROUTE_COST UCN_LINK_ROUTE_COST_UNKNOWN
#endif
#ifndef UCN_PENDING_Q1_DEPTH
#define UCN_PENDING_Q1_DEPTH ((size_t)4U)
#endif
#ifndef UCN_PENDING_Q1_TIMEOUT_MS
#define UCN_PENDING_Q1_TIMEOUT_MS UINT32_C(1000)
#endif
#ifndef UCN_SEQUENCE_ROTATION_THRESHOLD
#define UCN_SEQUENCE_ROTATION_THRESHOLD (UINT32_MAX - UINT32_C(1024))
#endif

/* Local-origin and inbound control-plane budgets. */
#ifndef UCN_CONTROL_TOKEN_BURST
#define UCN_CONTROL_TOKEN_BURST ((uint8_t)4U)
#endif
#ifndef UCN_CONTROL_TOKEN_REFILL_MS
#define UCN_CONTROL_TOKEN_REFILL_MS UINT32_C(100)
#endif
#ifndef UCN_ROUTE_REQUEST_RX_TOKEN_BURST
#define UCN_ROUTE_REQUEST_RX_TOKEN_BURST ((uint8_t)5U)
#endif
#ifndef UCN_ROUTE_REQUEST_RX_TOKEN_REFILL_MS
#define UCN_ROUTE_REQUEST_RX_TOKEN_REFILL_MS UINT32_C(200)
#endif
#ifndef UCN_HEARTBEAT_RX_TOKEN_BURST
#define UCN_HEARTBEAT_RX_TOKEN_BURST ((uint8_t)4U)
#endif
#ifndef UCN_HEARTBEAT_RX_TOKEN_REFILL_MS
#define UCN_HEARTBEAT_RX_TOKEN_REFILL_MS UINT32_C(100)
#endif
#ifndef UCN_PATH_TRACE_RX_TOKEN_BURST
#define UCN_PATH_TRACE_RX_TOKEN_BURST ((uint8_t)1U)
#endif
#ifndef UCN_PATH_TRACE_RX_TOKEN_REFILL_MS
#define UCN_PATH_TRACE_RX_TOKEN_REFILL_MS UINT32_C(1000)
#endif
#ifndef UCN_PATH_CONTROL_RX_SOURCE_DEPTH
#define UCN_PATH_CONTROL_RX_SOURCE_DEPTH ((size_t)4U)
#endif
#ifndef UCN_PATH_CONTROL_RX_TOKEN_BURST
#define UCN_PATH_CONTROL_RX_TOKEN_BURST ((uint8_t)4U)
#endif
#ifndef UCN_PATH_CONTROL_RX_TOKEN_REFILL_MS
#define UCN_PATH_CONTROL_RX_TOKEN_REFILL_MS UINT32_C(1000)
#endif
#ifndef UCN_PATH_CONTROL_RX_SOURCE_IDLE_MS
#define UCN_PATH_CONTROL_RX_SOURCE_IDLE_MS UINT32_C(60000)
#endif

/* On-demand path, snapshot and policy diagnostics. */
#ifndef UCN_PATH_TRACE_PENDING_DEPTH
#define UCN_PATH_TRACE_PENDING_DEPTH ((size_t)2U)
#endif
#ifndef UCN_PATH_TRACE_REVERSE_DEPTH
#define UCN_PATH_TRACE_REVERSE_DEPTH ((size_t)4U)
#endif
#ifndef UCN_PATH_TRACE_TIMEOUT_MS
#define UCN_PATH_TRACE_TIMEOUT_MS UINT32_C(1000)
#endif
#ifndef UCN_PATH_TRACE_TOKEN_BURST
#define UCN_PATH_TRACE_TOKEN_BURST ((uint8_t)1U)
#endif
#ifndef UCN_PATH_TRACE_TOKEN_REFILL_MS
#define UCN_PATH_TRACE_TOKEN_REFILL_MS UINT32_C(1000)
#endif
#ifndef UCN_NODE_SNAPSHOT_MAX_RESULTS
#define UCN_NODE_SNAPSHOT_MAX_RESULTS ((size_t)8U)
#endif
#ifndef UCN_NODE_SNAPSHOT_PENDING_DEPTH
#define UCN_NODE_SNAPSHOT_PENDING_DEPTH ((size_t)1U)
#endif
#ifndef UCN_NODE_SNAPSHOT_REVERSE_DEPTH
#define UCN_NODE_SNAPSHOT_REVERSE_DEPTH ((size_t)2U)
#endif
#ifndef UCN_NODE_SNAPSHOT_REPLY_QUEUE_DEPTH
#define UCN_NODE_SNAPSHOT_REPLY_QUEUE_DEPTH ((size_t)2U)
#endif
#ifndef UCN_NODE_SNAPSHOT_TIMEOUT_MS
#define UCN_NODE_SNAPSHOT_TIMEOUT_MS UINT32_C(2000)
#endif
#ifndef UCN_NODE_SNAPSHOT_TOKEN_BURST
#define UCN_NODE_SNAPSHOT_TOKEN_BURST ((uint8_t)1U)
#endif
#ifndef UCN_NODE_SNAPSHOT_TOKEN_REFILL_MS
#define UCN_NODE_SNAPSHOT_TOKEN_REFILL_MS UINT32_C(10000)
#endif
#ifndef UCN_NODE_SNAPSHOT_REPLY_JITTER_MS
#define UCN_NODE_SNAPSHOT_REPLY_JITTER_MS UINT32_C(200)
#endif
#ifndef UCN_POLICY_DIAGNOSTIC_PENDING_DEPTH
#define UCN_POLICY_DIAGNOSTIC_PENDING_DEPTH ((size_t)2U)
#endif
#ifndef UCN_POLICY_DIAGNOSTIC_REPLY_QUEUE_DEPTH
#define UCN_POLICY_DIAGNOSTIC_REPLY_QUEUE_DEPTH ((size_t)2U)
#endif
#ifndef UCN_POLICY_DIAGNOSTIC_TIMEOUT_MS
#define UCN_POLICY_DIAGNOSTIC_TIMEOUT_MS UINT32_C(1000)
#endif
#ifndef UCN_POLICY_DIAGNOSTIC_TOKEN_BURST
#define UCN_POLICY_DIAGNOSTIC_TOKEN_BURST ((uint8_t)1U)
#endif
#ifndef UCN_POLICY_DIAGNOSTIC_TOKEN_REFILL_MS
#define UCN_POLICY_DIAGNOSTIC_TOKEN_REFILL_MS UINT32_C(1000)
#endif

/* Neighbor, heartbeat and multi-bearer quality. */
#ifndef UCN_MAX_NEIGHBORS
#define UCN_MAX_NEIGHBORS ((size_t)8U)
#endif
#ifndef UCN_MAX_BEARERS_PER_NEIGHBOR
#define UCN_MAX_BEARERS_PER_NEIGHBOR ((size_t)2U)
#endif
#ifndef UCN_NEIGHBOR_CANDIDATE_TIMEOUT_MS
#define UCN_NEIGHBOR_CANDIDATE_TIMEOUT_MS UINT32_C(5000)
#endif
#ifndef UCN_HEARTBEAT_INTERVAL_MS
#define UCN_HEARTBEAT_INTERVAL_MS UINT32_C(1000)
#endif
#ifndef UCN_NEIGHBOR_SUSPECT_TIMEOUT_MS
#define UCN_NEIGHBOR_SUSPECT_TIMEOUT_MS UINT32_C(3000)
#endif
#ifndef UCN_NEIGHBOR_REMOVE_TIMEOUT_MS
#define UCN_NEIGHBOR_REMOVE_TIMEOUT_MS UINT32_C(4000)
#endif
#ifndef UCN_BEARER_SWITCH_IMPROVEMENT_PERCENT
#define UCN_BEARER_SWITCH_IMPROVEMENT_PERCENT \
    UCN_ROUTE_SWITCH_IMPROVEMENT_PERCENT
#endif
#ifndef UCN_BEARER_QUALITY_SAMPLE_INTERVAL_MS
#define UCN_BEARER_QUALITY_SAMPLE_INTERVAL_MS UINT32_C(500)
#endif
#ifndef UCN_BEARER_QUALITY_STABLE_SAMPLES
#define UCN_BEARER_QUALITY_STABLE_SAMPLES ((uint8_t)3U)
#endif
#ifndef UCN_BEARER_QUALITY_PROBE_REQUIRED_ACKS
#define UCN_BEARER_QUALITY_PROBE_REQUIRED_ACKS ((uint8_t)2U)
#endif
#ifndef UCN_BEARER_QUALITY_PROBE_MAX_ATTEMPTS
#define UCN_BEARER_QUALITY_PROBE_MAX_ATTEMPTS ((uint8_t)3U)
#endif
#ifndef UCN_BEARER_QUALITY_PROBE_INTERVAL_MS
#define UCN_BEARER_QUALITY_PROBE_INTERVAL_MS UINT32_C(100)
#endif

/* Endpoint, explicit Path and policy tables. */
#ifndef UCN_MAX_ENDPOINT_HANDLERS
#define UCN_MAX_ENDPOINT_HANDLERS ((size_t)8U)
#endif
#ifndef UCN_MAX_ENDPOINT_SECURITY_POLICIES
#define UCN_MAX_ENDPOINT_SECURITY_POLICIES ((size_t)8U)
#endif
#ifndef UCN_MAX_PATH_FORWARD_ENTRIES
#define UCN_MAX_PATH_FORWARD_ENTRIES ((size_t)8U)
#endif
#ifndef UCN_MAX_ROUTE_POLICIES
#define UCN_MAX_ROUTE_POLICIES ((size_t)8U)
#endif
#ifndef UCN_MAX_POLICY_PATHS
#define UCN_MAX_POLICY_PATHS ((size_t)8U)
#endif
#ifndef UCN_MAX_POLICY_FLOWS
#define UCN_MAX_POLICY_FLOWS ((size_t)8U)
#endif
#ifndef UCN_POLICY_QUALITY_SAMPLE_INTERVAL_MS
#define UCN_POLICY_QUALITY_SAMPLE_INTERVAL_MS UINT32_C(500)
#endif
#ifndef UCN_POLICY_QUALITY_EWMA_ALPHA_PERCENT
#define UCN_POLICY_QUALITY_EWMA_ALPHA_PERCENT ((uint8_t)25U)
#endif
#ifndef UCN_POLICY_BALANCE_FLOW_LEASE_MS
#define UCN_POLICY_BALANCE_FLOW_LEASE_MS UINT32_C(2000)
#endif
#ifndef UCN_POLICY_BALANCE_QUEUE_PRESSURE_THRESHOLD_PER_MILLE
#define UCN_POLICY_BALANCE_QUEUE_PRESSURE_THRESHOLD_PER_MILLE ((uint16_t)800U)
#endif
#ifndef UCN_POLICY_BALANCE_CONGESTED_SAMPLE_LIMIT
#define UCN_POLICY_BALANCE_CONGESTED_SAMPLE_LIMIT ((uint8_t)3U)
#endif

/* Intra-node Service Router and Protocol Bridge. */
#ifndef UCN_SERVICE_MAX_BINDINGS
#define UCN_SERVICE_MAX_BINDINGS ((uint8_t)6U)
#endif
#ifndef UCN_SERVICE_MAX_PAYLOAD_BYTES
#define UCN_SERVICE_MAX_PAYLOAD_BYTES ((uint16_t)32U)
#endif
#ifndef UCN_SERVICE_REMOTE_TX_Q0_DEPTH
#define UCN_SERVICE_REMOTE_TX_Q0_DEPTH ((uint8_t)4U)
#endif
#ifndef UCN_SERVICE_REMOTE_TX_Q1_DEPTH
#define UCN_SERVICE_REMOTE_TX_Q1_DEPTH ((uint8_t)4U)
#endif
#ifndef UCN_SERVICE_MAX_Q0_BINDINGS
#define UCN_SERVICE_MAX_Q0_BINDINGS ((uint8_t)2U)
#endif
#ifndef UCN_SERVICE_MAX_Q1_BINDINGS
#define UCN_SERVICE_MAX_Q1_BINDINGS ((uint8_t)4U)
#endif
#ifndef UCN_SERVICE_Q0_INBOX_DEPTH
#define UCN_SERVICE_Q0_INBOX_DEPTH ((uint8_t)4U)
#endif
#ifndef UCN_SERVICE_BRIDGE_MAX_VALIDATORS
#define UCN_SERVICE_BRIDGE_MAX_VALIDATORS UCN_SERVICE_MAX_Q0_BINDINGS
#endif
#ifndef UCN_SERVICE_BRIDGE_REPLAY_DEPTH
#define UCN_SERVICE_BRIDGE_REPLAY_DEPTH ((uint8_t)4U)
#endif

#endif /* UCN_CONFIG_NO_DEFAULTS */

#endif /* UCN_CONFIG_H */
