#include "internal/ucn_digest.h"
#include "internal/ucn_realtime.h"

#include <stdio.h>
#include <string.h>

#define CHECK(x)do{if(!(x))return __LINE__;}while(0)
typedef struct L{uint8_t h;}L;static L l;static ucn_i_realtime_owner_t o;
static ucn_result_t e(void*c){L*x=c;if(x==NULL||x->h)return UCN_ERR_STATE;x->h=1U;return UCN_OK;}static void q(void*c){((L*)c)->h=0U;}
static ucn_i_lock_ops_t lo(void){ucn_i_lock_ops_t x;memset(&x,0,sizeof(x));x.struct_size=sizeof(x);x.api_version=1U;x.context=&l;x.enter=e;x.leave=q;return x;}
static ucn_i_realtime_domain_config_t dc(void){ucn_i_realtime_domain_config_t c;memset(&c,0,sizeof(c));c.clock_domain_id=7U;c.domain_generation=1U;c.lock_sample_count=1U;c.sync_timeout_us=100U;c.max_holdover_us=200U;c.oscillator_uncertainty_ppb=1U;c.max_offset_jump_us=100U;c.base_uncertainty.known_mask=63U;c.base_uncertainty.timer_resolution_bound_us=1U;c.base_uncertainty.link_timestamp_capture_bound_us=1U;c.base_uncertainty.filter_residual_bound_us=1U;c.base_uncertainty.arithmetic_rounding_bound_us=1U;c.base_uncertainty.sample_capture_bound_us=1U;c.base_uncertainty.path_asymmetry_bound_us=1U;c.path.route_causal_id=1U;c.path.route_generation=1U;c.path.session_generation=1U;c.path.capability_generation=1U;c.path.forward_link_generation=1U;c.path.reverse_link_generation=2U;c.path.forward_link_id=1U;c.path.reverse_link_id=2U;memset(c.path.capability_digest,1,16U);c.path.authenticated=1U;c.path.frozen=1U;c.path.directional=1U;c.path.asymmetry_known=1U;c.path.max_asymmetry_us=1U;return c;}
static int setup(void){ucn_i_realtime_config_t c;ucn_i_realtime_domain_config_t d=dc();ucn_i_realtime_durability_t u;ucn_i_realtime_requirement_t r;ucn_i_realtime_proof_t p;ucn_i_sha256_workspace_t w;ucn_i_realtime_sync_sample_t s;ucn_handle_t h,ph;memset(&o,0,sizeof(o));memset(&l,0,sizeof(l));memset(&c,0,sizeof(c));c.runtime_instance=1U;c.owner_instance=8U;c.state_lock=lo();CHECK(ucn_i_realtime_owner_init(&o,&c)==UCN_OK);memset(&u,0,sizeof(u));u.domain_id=1U;u.foundation_transaction_id=1U;u.absolute_deadline_us=999U;u.persistence_domain_generation=4U;u.schema_id=UCN_I_REALTIME_DOMAIN_SCHEMA_ID;u.schema_version=1U;u.volatile_continuation.runtime_instance=1U;u.volatile_continuation.owner_instance=8U;u.volatile_continuation.slot=1U;u.volatile_continuation.generation=1U;u.volatile_continuation.object_kind=UCN_OBJECT_KIND_TIME_DOMAIN;CHECK(ucn_i_realtime_domain_prepare(&o,&d,&u,&h,&r)==UCN_OK);memset(&p,0,sizeof(p));memset(&w,0,sizeof(w));memset(&ph,0,sizeof(ph));ph.runtime_instance=1U;ph.owner_instance=9U;ph.slot=1U;ph.generation=1U;ph.object_kind=UCN_OBJECT_KIND_PERSISTENCE;CHECK(ucn_i_sha256_128(r.body,r.body_bytes,p.body_digest,&w)==UCN_OK);CHECK(ucn_i_realtime_domain_bind_persistence(&o,h,ph,p.body_digest)==UCN_OK);p.persistence_handle=ph;p.domain_id=1U;p.foundation_transaction_id=1U;p.record_generation=1U;p.witness_generation=1U;p.runtime_instance=1U;p.body_bytes=128U;p.persistence_domain_generation=4U;p.persistence_owner_instance=9U;p.caller_owner_instance=8U;p.schema_id=UCN_I_REALTIME_DOMAIN_SCHEMA_ID;p.schema_version=1U;p.operation_kind=UCN_I_REALTIME_DOMAIN_PERSIST_KIND;CHECK(ucn_i_realtime_domain_accept_proof(&o,h,&p,10U)==UCN_OK);memset(&s,0,sizeof(s));s.path=d.path;s.offset_us=100;s.sample_local_us=1000U;s.uncertainty_us=10U;s.clock_domain_id=7U;s.valid_sync_sample=1U;CHECK(ucn_i_realtime_domain_accept_sample(&o,&s)==UCN_OK);return 0;}
static int test_prepare_modes(void){ucn_i_realtime_policy_t p;ucn_i_realtime_prepared_t x;memset(&p,0,sizeof(p));p.endpoint=1U;p.mode=UCN_I_REALTIME_NONE;CHECK(ucn_i_realtime_policy_set(&o,&p)==UCN_OK);CHECK(ucn_i_realtime_prepare(&o,1U,1001U,0U,false,(ucn_i_realtime_prepared_t *)&o)==UCN_ERR_ARGUMENT);CHECK(ucn_i_realtime_prepare(&o,1U,1001U,0U,false,&x)==UCN_OK&&!x.metadata_present);memset(&p,0,sizeof(p));p.endpoint=2U;p.mode=UCN_I_REALTIME_LOCAL_STAMP;p.requirement=UCN_I_REALTIME_REQUIRED;CHECK(ucn_i_realtime_policy_set(&o,&p)==UCN_OK);CHECK(ucn_i_realtime_prepare(&o,2U,1001U,0U,false,&x)==UCN_OK&&x.envelope.mode==UCN_I_REALTIME_LOCAL_STAMP);memset(&p,0,sizeof(p));p.endpoint=3U;p.mode=UCN_I_REALTIME_DEADLINE;p.requirement=UCN_I_REALTIME_REQUIRED;p.clock_domain_id=7U;p.max_age_us=100U;p.max_uncertainty_us=100U;CHECK(ucn_i_realtime_policy_set(&o,&p)==UCN_OK);CHECK(ucn_i_realtime_prepare(&o,3U,1001U,5U,false,&x)==UCN_OK&&x.envelope.mode==UCN_I_REALTIME_DEADLINE&&x.envelope.capture_time_us==1101U);return 0;}
static int test_double_gate_and_security(void){ucn_i_realtime_receive_facts_t f;ucn_i_realtime_receive_view_t v;ucn_i_realtime_prepared_t p;uint64_t capture;CHECK(ucn_i_realtime_prepare(&o,3U,1002U,5U,false,&p)==UCN_OK);memset(&f,0,sizeof(f));f.envelope=p.envelope;capture=f.envelope.capture_time_us;f.local_now_us=1003U;f.endpoint=3U;f.metadata_present=1U;f.e2e_authenticated=1U;f.source_acl_authorized=1U;CHECK(ucn_i_realtime_admit(&o,&f,&v)==UCN_OK&&v.accepted);f.source_acl_authorized=0U;CHECK(ucn_i_realtime_admit(&o,&f,&v)==UCN_ERR_POLICY&&v.reason==UCN_I_REALTIME_REJECT_SECURITY);f.source_acl_authorized=1U;f.envelope.capture_time_us=2000U;CHECK(ucn_i_realtime_admit(&o,&f,&v)==UCN_ERR_POLICY&&v.reason==UCN_I_REALTIME_REJECT_FUTURE);f.envelope.capture_time_us=capture;f.local_now_us=1200U;CHECK(ucn_i_realtime_admit(&o,&f,&v)==UCN_ERR_POLICY&&v.reason==UCN_I_REALTIME_REJECT_EXPIRED);return 0;}
static int test_local_stamp_requires_security(void){ucn_i_realtime_receive_facts_t f;ucn_i_realtime_receive_view_t v;ucn_i_realtime_prepared_t p;CHECK(ucn_i_realtime_prepare(&o,2U,1004U,0U,false,&p)==UCN_OK);memset(&f,0,sizeof(f));f.envelope=p.envelope;f.local_now_us=1005U;f.endpoint=2U;f.metadata_present=1U;CHECK(ucn_i_realtime_admit(&o,&f,&v)==UCN_ERR_POLICY&&v.reason==UCN_I_REALTIME_REJECT_SECURITY);f.e2e_authenticated=1U;f.source_acl_authorized=1U;CHECK(ucn_i_realtime_admit(&o,&f,&v)==UCN_OK&&v.accepted);return 0;}
int main(void){int r=setup();if(r==0)r=test_prepare_modes();if(r==0)r=test_double_gate_and_security();if(r==0)r=test_local_stamp_requires_security();if(r!=0)fprintf(stderr,"realtime policy failed: %d\n",r);return r;}
