#include "internal/ucn_digest.h"
#include "internal/ucn_realtime.h"

#include <stdio.h>
#include <string.h>

#define CHECK(x) do{if(!(x))return __LINE__;}while(0)
typedef struct test_lock{uint8_t held;}test_lock_t;
static test_lock_t lock_state;static ucn_i_realtime_owner_t owner;
static ucn_result_t enter(void*c){test_lock_t*l=c;if(l==NULL||l->held)return UCN_ERR_STATE;l->held=1U;return UCN_OK;}static void leave(void*c){((test_lock_t*)c)->held=0U;}
static ucn_i_lock_ops_t lock_ops(void){ucn_i_lock_ops_t l;memset(&l,0,sizeof(l));l.struct_size=sizeof(l);l.api_version=UCN_I_LOCK_OPS_VERSION;l.context=&lock_state;l.enter=enter;l.leave=leave;return l;}
static ucn_i_realtime_domain_config_t config(void){ucn_i_realtime_domain_config_t c;memset(&c,0,sizeof(c));c.clock_domain_id=7U;c.domain_generation=1U;c.lock_sample_count=1U;c.sync_timeout_us=100U;c.max_holdover_us=200U;c.max_offset_jump_us=1000U;c.oscillator_uncertainty_ppb=1U;c.base_uncertainty.known_mask=UCN_I_REALTIME_KNOWN_ALL;c.base_uncertainty.timer_resolution_bound_us=1U;c.base_uncertainty.link_timestamp_capture_bound_us=1U;c.base_uncertainty.filter_residual_bound_us=1U;c.base_uncertainty.arithmetic_rounding_bound_us=1U;c.base_uncertainty.sample_capture_bound_us=1U;c.base_uncertainty.path_asymmetry_bound_us=5U;c.path.route_causal_id=10U;c.path.route_generation=11U;c.path.session_generation=12U;c.path.capability_generation=13U;c.path.forward_link_generation=14U;c.path.reverse_link_generation=15U;c.path.forward_link_id=1U;c.path.reverse_link_id=2U;memset(c.path.capability_digest,0xA5,16U);c.path.authenticated=1U;c.path.frozen=1U;c.path.directional=1U;c.path.asymmetry_known=1U;c.path.max_asymmetry_us=5U;return c;}
static int setup(void){ucn_i_realtime_config_t cfg;ucn_i_realtime_domain_config_t c=config();ucn_i_realtime_durability_t d;ucn_i_realtime_requirement_t r;ucn_i_realtime_proof_t p;ucn_i_sha256_workspace_t w;ucn_handle_t h,ph;memset(&owner,0,sizeof(owner));memset(&lock_state,0,sizeof(lock_state));memset(&cfg,0,sizeof(cfg));cfg.runtime_instance=1U;cfg.owner_instance=8U;cfg.state_lock=lock_ops();CHECK(ucn_i_realtime_owner_init(&owner,&cfg)==UCN_OK);memset(&d,0,sizeof(d));d.domain_id=800U;d.foundation_transaction_id=1U;d.absolute_deadline_us=999U;d.volatile_continuation.runtime_instance=1U;d.volatile_continuation.owner_instance=8U;d.volatile_continuation.slot=1U;d.volatile_continuation.generation=1U;d.volatile_continuation.object_kind=UCN_OBJECT_KIND_TIME_DOMAIN;d.persistence_domain_generation=4U;d.schema_id=UCN_I_REALTIME_DOMAIN_SCHEMA_ID;d.schema_version=UCN_I_REALTIME_DOMAIN_RECORD_SCHEMA;CHECK(ucn_i_realtime_domain_prepare(&owner,&c,&d,&h,&r)==UCN_OK);memset(&p,0,sizeof(p));memset(&ph,0,sizeof(ph));memset(&w,0,sizeof(w));ph.runtime_instance=1U;ph.owner_instance=9U;ph.slot=1U;ph.generation=1U;ph.object_kind=UCN_OBJECT_KIND_PERSISTENCE;CHECK(ucn_i_sha256_128(r.body,r.body_bytes,p.body_digest,&w)==UCN_OK);CHECK(ucn_i_realtime_domain_bind_persistence(&owner,h,ph,p.body_digest)==UCN_OK);p.persistence_handle=ph;p.domain_id=800U;p.foundation_transaction_id=1U;p.record_generation=1U;p.witness_generation=1U;p.runtime_instance=1U;p.body_bytes=128U;p.persistence_domain_generation=4U;p.persistence_owner_instance=9U;p.caller_owner_instance=8U;p.schema_id=UCN_I_REALTIME_DOMAIN_SCHEMA_ID;p.schema_version=1U;p.operation_kind=UCN_I_REALTIME_DOMAIN_PERSIST_KIND;CHECK(ucn_i_realtime_domain_accept_proof(&owner,h,&p,10U)==UCN_OK);return 0;}
static ucn_i_realtime_sync_announce_t announce(uint32_t seq){ucn_i_realtime_sync_announce_t a;memset(&a,0,sizeof(a));a.path=config().path;a.t2_member_rx.link_generation=14U;a.t2_member_rx.token=100U+seq;a.t2_member_rx.link_id=1U;a.t2_member_rx.direction=UCN_I_REALTIME_EVENT_RX;a.t2_member_rx_us=110U;a.absolute_deadline_us=500U;a.domain_generation=1U;a.sync_sequence=seq;a.t2_uncertainty_us=2U;a.clock_domain_id=7U;return a;}
static ucn_i_realtime_event_key_t t3key(uint32_t token){ucn_i_realtime_event_key_t k;memset(&k,0,sizeof(k));k.link_generation=15U;k.token=token;k.link_id=2U;k.direction=UCN_I_REALTIME_EVENT_TX;return k;}
static int test_complete_and_release_retry(void){ucn_i_realtime_sync_announce_t a=announce(1U);ucn_i_realtime_sync_response_t r;ucn_i_realtime_event_key_t k=t3key(201U);ucn_i_realtime_release_view_t first,retry,second;ucn_i_realtime_clock_view_t clock;ucn_handle_t h;CHECK(ucn_i_realtime_sync_begin(&owner,&a,(ucn_handle_t *)&owner)==UCN_ERR_ARGUMENT);CHECK(ucn_i_realtime_sync_begin(&owner,&a,&h)==UCN_OK);CHECK(ucn_i_realtime_sync_bind_t3(&owner,h,&k,120U,2U)==UCN_OK);memset(&r,0,sizeof(r));r.path=a.path;r.t1_master_tx_us=100U;r.t4_master_rx_us=130U;r.domain_generation=1U;r.sync_sequence=1U;r.t1_uncertainty_us=2U;r.t4_uncertainty_us=2U;r.clock_domain_id=7U;CHECK(ucn_i_realtime_sync_complete(&owner,h,&r,131U)==UCN_OK);CHECK(ucn_i_realtime_domain_get_clock(&owner,7U,121U,&clock)==UCN_OK);CHECK(clock.domain_time_us==121U);CHECK(ucn_i_realtime_release_peek(&owner,&first)==UCN_OK);CHECK(ucn_i_realtime_release_peek(&owner,&second)==UCN_OK);CHECK(first.key.token!=second.key.token);retry=first;retry.key.token++;CHECK(ucn_i_realtime_release_ack(&owner,&retry)==UCN_ERR_STATE);CHECK(ucn_i_realtime_release_ack(&owner,&first)==UCN_OK);CHECK(ucn_i_realtime_release_ack(&owner,&second)==UCN_OK);return 0;}
static int test_replace_and_timeout(void){ucn_i_realtime_sync_announce_t a=announce(2U),b=announce(3U);ucn_i_realtime_release_view_t rel;ucn_i_realtime_event_key_t k=t3key(202U);ucn_handle_t h1,h2;CHECK(ucn_i_realtime_sync_begin(&owner,&a,&h1)==UCN_OK);CHECK(ucn_i_realtime_sync_bind_t3(&owner,h1,&k,120U,2U)==UCN_OK);CHECK(ucn_i_realtime_sync_begin(&owner,&b,&h2)==UCN_OK);CHECK(ucn_i_realtime_sync_bind_t3(&owner,h1,&k,120U,2U)==UCN_ERR_STATE);CHECK(ucn_i_realtime_release_peek(&owner,&rel)==UCN_OK);CHECK(ucn_i_realtime_release_ack(&owner,&rel)==UCN_OK);CHECK(ucn_i_realtime_release_peek(&owner,&rel)==UCN_OK);CHECK(ucn_i_realtime_release_ack(&owner,&rel)==UCN_OK);CHECK(ucn_i_realtime_step(&owner,500U)==UCN_OK);CHECK(ucn_i_realtime_release_peek(&owner,&rel)==UCN_OK&&rel.key.token==103U);CHECK(ucn_i_realtime_release_ack(&owner,&rel)==UCN_OK);return 0;}
static int test_late_response_is_rejected(void){ucn_i_realtime_sync_announce_t a=announce(4U);ucn_i_realtime_sync_response_t r;ucn_i_realtime_event_key_t k=t3key(204U);ucn_i_realtime_release_view_t rel;ucn_handle_t h;CHECK(ucn_i_realtime_sync_begin(&owner,&a,&h)==UCN_OK);CHECK(ucn_i_realtime_sync_bind_t3(&owner,h,&k,120U,2U)==UCN_OK);memset(&r,0,sizeof(r));r.path=a.path;r.t1_master_tx_us=100U;r.t4_master_rx_us=130U;r.domain_generation=1U;r.sync_sequence=4U;r.t1_uncertainty_us=2U;r.t4_uncertainty_us=2U;r.clock_domain_id=7U;CHECK(ucn_i_realtime_sync_complete(&owner,h,&r,500U)==UCN_ERR_STATE);CHECK(ucn_i_realtime_step(&owner,500U)==UCN_OK);CHECK(ucn_i_realtime_release_peek(&owner,&rel)==UCN_OK);CHECK(ucn_i_realtime_release_ack(&owner,&rel)==UCN_OK);CHECK(ucn_i_realtime_release_peek(&owner,&rel)==UCN_OK);CHECK(ucn_i_realtime_release_ack(&owner,&rel)==UCN_OK);return 0;}
int main(void){int r=setup();if(r==0)r=test_complete_and_release_retry();if(r==0)r=test_replace_and_timeout();if(r==0)r=test_late_response_is_rejected();if(r!=0)fprintf(stderr,"realtime sync failed: %d\n",r);return r;}
