#ifndef UCN_TEST_USER_CONFIG_H
#define UCN_TEST_USER_CONFIG_H

/* Representative product overrides.  Unlisted values must continue to use
 * the defaults in ucn_config.h. */
#ifndef UCN_MAX_FRAME_BYTES
#define UCN_MAX_FRAME_BYTES ((size_t)128U)
#endif
#ifndef UCN_MAX_PAYLOAD_BYTES
#define UCN_MAX_PAYLOAD_BYTES ((size_t)64U)
#endif
#ifndef UCN_MAX_HOPS
#define UCN_MAX_HOPS ((uint8_t)8U)
#endif
#ifndef UCN_TRANSFER_MAX_MESSAGE_BYTES
#define UCN_TRANSFER_MAX_MESSAGE_BYTES ((size_t)512U)
#endif
#ifndef UCN_TRANSFER_RX_SLOTS
#define UCN_TRANSFER_RX_SLOTS ((size_t)2U)
#endif
#ifndef UCN_TRANSFER_MAX_WINDOW
#define UCN_TRANSFER_MAX_WINDOW ((uint8_t)2U)
#endif
#ifndef UCN_ADAPTER_RX_QUEUE_DEPTH
#define UCN_ADAPTER_RX_QUEUE_DEPTH 3U
#endif
#ifndef UCN_EVENT_RUNTIME_MAX_SOURCES
#define UCN_EVENT_RUNTIME_MAX_SOURCES 3U
#endif
#ifndef UCN_EVENT_RUNTIME_DEFAULT_DRAIN_ROUNDS
#define UCN_EVENT_RUNTIME_DEFAULT_DRAIN_ROUNDS 5U
#endif
#ifndef UCN_EVENT_RUNTIME_DEFAULT_SOURCE_BUDGET
#define UCN_EVENT_RUNTIME_DEFAULT_SOURCE_BUDGET 2U
#endif
#ifndef UCN_STREAM_SOURCE_DEFAULT_RING_BYTES
#define UCN_STREAM_SOURCE_DEFAULT_RING_BYTES 128U
#endif
#ifndef UCN_STREAM_SOURCE_DEFAULT_BYTE_BUDGET
#define UCN_STREAM_SOURCE_DEFAULT_BYTE_BUDGET 64U
#endif
#ifndef UCN_STREAM_SOURCE_DEFAULT_ERROR_BUDGET
#define UCN_STREAM_SOURCE_DEFAULT_ERROR_BUDGET 2U
#endif
#ifndef UCN_CAN_SOURCE_DEFAULT_RING_FRAMES
#define UCN_CAN_SOURCE_DEFAULT_RING_FRAMES 4U
#endif
#ifndef UCN_CAN_SOURCE_DEFAULT_REASSEMBLY_SLOTS
#define UCN_CAN_SOURCE_DEFAULT_REASSEMBLY_SLOTS 1U
#endif
#ifndef UCN_CAN_SOURCE_DEFAULT_REASSEMBLY_TIMEOUT_MS
#define UCN_CAN_SOURCE_DEFAULT_REASSEMBLY_TIMEOUT_MS 75U
#endif
#ifndef UCN_STREAM_SOURCE_READ_CHUNK_BYTES
#define UCN_STREAM_SOURCE_READ_CHUNK_BYTES 16U
#endif
#ifndef UCN_MAX_LINKS
#define UCN_MAX_LINKS ((size_t)3U)
#endif
#ifndef UCN_TX_Q0_DEPTH
#define UCN_TX_Q0_DEPTH ((size_t)2U)
#endif
#ifndef UCN_MAX_NEIGHBORS
#define UCN_MAX_NEIGHBORS ((size_t)4U)
#endif
#ifndef UCN_MAX_BEARERS_PER_NEIGHBOR
#define UCN_MAX_BEARERS_PER_NEIGHBOR ((size_t)1U)
#endif
#ifndef UCN_PATH_ACTIVATE_ACK_TIMEOUT_MS
#define UCN_PATH_ACTIVATE_ACK_TIMEOUT_MS UINT32_C(800)
#endif
#ifndef UCN_PATH_ACTIVATE_RETRY_INTERVAL_MS
#define UCN_PATH_ACTIVATE_RETRY_INTERVAL_MS UINT32_C(200)
#endif
#ifndef UCN_PATH_ACTIVATE_MAX_RETRIES
#define UCN_PATH_ACTIVATE_MAX_RETRIES ((uint8_t)3U)
#endif
#ifndef UCN_CLUSTER_MAX_PEERS
#define UCN_CLUSTER_MAX_PEERS ((size_t)4U)
#endif
#ifndef UCN_CLUSTER_MAX_CANDIDATES
#define UCN_CLUSTER_MAX_CANDIDATES ((size_t)3U)
#endif
#ifndef UCN_CLUSTER_MAX_MEMBERS
#define UCN_CLUSTER_MAX_MEMBERS ((size_t)6U)
#endif
#ifndef UCN_CLUSTER_LEASE_MS
#define UCN_CLUSTER_LEASE_MS UINT32_C(6000)
#endif
#ifndef UCN_CLUSTER_RECOVERY_OBSERVATION_MS
#define UCN_CLUSTER_RECOVERY_OBSERVATION_MS UINT32_C(4000)
#endif
#ifndef UCN_CLUSTER_FED_MAX_DIRECTORY_RECORDS
#define UCN_CLUSTER_FED_MAX_DIRECTORY_RECORDS ((size_t)9U)
#endif
#ifndef UCN_CLUSTER_FED_MAX_LOCATOR_CACHE
#define UCN_CLUSTER_FED_MAX_LOCATOR_CACHE ((size_t)5U)
#endif
#ifndef UCN_SERVICE_MAX_BINDINGS
#define UCN_SERVICE_MAX_BINDINGS ((uint8_t)4U)
#endif
#ifndef UCN_SERVICE_MAX_Q0_BINDINGS
#define UCN_SERVICE_MAX_Q0_BINDINGS ((uint8_t)1U)
#endif
#ifndef UCN_SERVICE_MAX_Q1_BINDINGS
#define UCN_SERVICE_MAX_Q1_BINDINGS ((uint8_t)3U)
#endif
#ifndef UCN_SERVICE_BRIDGE_MAX_VALIDATORS
#define UCN_SERVICE_BRIDGE_MAX_VALIDATORS ((uint8_t)1U)
#endif

#endif
